title: James Michael Maltby
subtitle: Learning technologist &amp; educational researcher<br/>Learning technology manager at <a href="https://www.plumpton.ac.uk">Plumpton College</a>
description: Award-winning learning technologist and educational researcher specialising in blended and immersive teaching. 
summary: James is an award-winning learning technologist and educational researcher specialising in blended and immersive teaching.<br/><br/>His work embedding virtual reality within teaching has been featured on BBC One Countryfile. He has presented research at the Association of Colleges, Blended Learning Consortium, Education & Training Foundation, and JISC. As a learning designer, he was worked with small businesses through to multinational companies, including British Airways and Tesco Booker.<br/><br/>In 2019, he was awarded a fellowship from the 1851 Royal Commission and the Education & Training Foundation to continue his research into how immersive technology is transforming technical teaching and STEM education.
url: https://www.jamesmichaelmaltby.com
enforce_ssl: www.jamesmichaelmaltby.com
email: hello@jamesmichaelmaltby.com
sass:
    style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
defaults:
  -
    scope:
      path:            "files/*"
    values:
      sitemap:         false
