title: James Michael Maltby
version: 20200106
subtitle: Learning technologist &amp; educational researcher
description: Award-winning learning technologist and educational researcher based in Brighton specialising in blended and immersive learning design
summary: I am an award-winning learning technologist and educational researcher specialising in blended and immersive learning design. My work embedding virtual reality within technical teaching was featured on BBC Countryfile. As well as working as a digital learning specialist within further and higher education, I have worked with small businesses through to multinational clients, including British Airways, National Trust and Tesco.<br/><br/>In 2019, I was awarded a awarded a fellowship from the 1851 Royal Commission and the Education & Training Foundation to continue my research into how immersive technology is transforming technical training.
url: https://www.jamesmichaelmaltby.com
enforce_ssl: www.jamesmichaelmaltby.com
email: hello@jamesmichaelmaltby.com
sass:
    style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
defaults:
  -
    scope:
      path:            "files/*"
    values:
      sitemap:         false
