title: James Michael Maltby
subtitle: Learning technologist &amp; educational researcher &middot; Learning technology manager at <a href="https://www.plumpton.ac.uk">Plumpton College</a>
description: I am a learning technologist on a mission to help everyone learn and work smarter through technology
summary: James is a learning technologist on a mission to help everyone learn and work smarter through technology. Current areas of research are the use of blended learning and virtual reality in the classroom. Recent speaking engagements include the Association of Colleges, Blended Learning Consortium and JISC.<br/><br/>Before working as a learning technologist, James was a special educational needs teacher supporting students on the autistic spectrum. He is a member of the Association for Learning Technology and National Autistic Society.
url: https://www.jamesmichaelmaltby.com
enforce_ssl: www.jamesmichaelmaltby.com
email: hello@jamesmichaelmaltby.com
sass:
    style: compressed
plugins:
  - jekyll-sitemap
